service: geo-api

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000

provider:
  architecture: arm64
  deploymentMethod: direct
  memorySize: 1024
  name: aws
  region: us-east-1
  runtime: nodejs18.x
  stage: v1
  versionFunctions: false

functions:
  location:
    handler: lib/api/lambda.handler
    events:
      - http:
          method: get
          path: location
